mycroft:
#  variables:
#    CI_DEBUG_TRACE: "true"
  tags:
    - barco, shell, ubuntu, desktop
  stage: deploy
  cache:
      paths:

  before_script:
    - set +e # Disable exit on error
    - whoami
    - if [ -e .env ]; then echo "Found .env"; else cp .env.sample .env; fi
    - source .env
    # - sudo bash ./scripts/before_script_install.sh
    - set -e # Enable exit on error 
  script: 
    - set +e # Disable exit on error
    - echo $PWD
    # echo " Assume user is gitlab-runner. If root, then sudo can be removed"
    - echo $USER
    - ip route show
    - ifconfig
    - sudo nmap -v localhost
    - sudo timedatectl set-timezone Asia/Taipei
    - sudo lsb_release -a
    - sudo uname -a
 
    - sudo docker --version
    - sudo docker images
    - sudo docker system df
    - sudo docker ps
    - sudo docker container ls -q

    # first stop docker process, clean up all stop images, containers
    - sudo docker stop  $(sudo docker container ls -aq --filter name=mycroft*);sudo docker container prune -f; sudo docker image prune -a -f
  
    - sudo docker run -v $PWD:/root/.mycroft --device /dev/snd -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native -v ~/.config/pulse/cookie:/root/.config/pulse/cookie -p 8181:8181 --name mycroft mycroftai/docker-mycroft
    - sudo chown -R gitlab-runner:gitlab-runner $PWD/*
    - set -e # Enable exit on error
  artifacts:
    name: "mycroft"
    untracked: true
    paths:
      - $PWD/data  ## Try to keep data even re-launch
      - $PWD/config
      - $PWD/logs
  after_script:
    - sudo chown -R gitlab-runner:gitlab-runner $PWD/*